exec-once = clipse -listen

windowrule = float true, match:class clipse
windowrule = size 622 652, match:class clipse
windowrule = center true, match:class clipse

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
